--Run these as user postgres:

--CREATE USER jtrack_usr WITH PASSWORD 'jtrack_pwd';
--CREATE DATABASE jtrack_db WITH OWNER jtrack_usr;

--connect to jtrack_db: \c jtrack_db jtrack_usr

--CREATE SCHEMA jtrack_sch AUTHORIZATION jtrack_usr;
--ALTER ROLE jtrack_usr SET search_path = jtrack_sch, "$user", public;
--run sql script: \i 'C:/WorkingDir/Projects/ProjectJTrackSample/dbScripts/JTrackScripts - pg.sql'


--DROP TABLE LOGIN_HIST;
--DROP TABLE TIMESHEET;
--DROP TABLE JOBS;
--DROP TABLE TIMESHEET_CODE;
--DROP TABLE JOB_STAGE;
--DROP TABLE JOB_RESOLUTION;
--DROP TABLE JOB_PRIORITY;
--DROP TABLE JOB_STATUS;
--DROP TABLE JOB_TYPE;
--DROP TABLE USERS;

--DROP SEQUENCE JOB_NO_SEQ;


CREATE TABLE JOB_TYPE(
  JOB_TYPE			VARCHAR(20),
  JOB_TYPE_DESC		VARCHAR(250),
  ACTIVE			BOOLEAN,
  DATE_CRT	      	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      	VARCHAR(20),
  DATE_MOD			TIMESTAMP,
  USER_MOD			VARCHAR(20)
);

ALTER TABLE JOB_TYPE ADD
  CONSTRAINT JOB_TYPE_PK
  PRIMARY KEY (JOB_TYPE);


CREATE TABLE JOB_STATUS(
  JOB_STATUS        VARCHAR(20),
  JOB_STATUS_DESC	VARCHAR(250),
  ACTIVE          	BOOLEAN,
  DATE_CRT	      	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      	VARCHAR(20),
  DATE_MOD			TIMESTAMP,
  USER_MOD			VARCHAR(20)
);

ALTER TABLE JOB_STATUS ADD
  CONSTRAINT JOB_STATUS_PK
  PRIMARY KEY (JOB_STATUS);
  
  
CREATE TABLE JOB_PRIORITY(
  JOB_PRIORITY      VARCHAR(10),
  JOB_PRIORITY_DESC	VARCHAR(250),
  ACTIVE          	BOOLEAN,
  DATE_CRT	      	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      	VARCHAR(20),
  DATE_MOD			TIMESTAMP,
  USER_MOD			VARCHAR(20)
);

ALTER TABLE JOB_PRIORITY ADD
  CONSTRAINT JOB_PRIORITY_PK
  PRIMARY KEY (JOB_PRIORITY);
  
  
CREATE TABLE JOB_RESOLUTION(
  JOB_RESOLUTION      	VARCHAR(20),
  JOB_RESOLUTION_DESC 	VARCHAR(250),
  ACTIVE          		BOOLEAN,
  DATE_CRT	      		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      		VARCHAR(20),
  DATE_MOD				TIMESTAMP,
  USER_MOD				VARCHAR(20)
);

ALTER TABLE JOB_RESOLUTION ADD
  CONSTRAINT JOB_RESOLUTION_PK
  PRIMARY KEY (JOB_RESOLUTION);
  
  
CREATE TABLE JOB_STAGE(
  JOB_STAGE         VARCHAR(20),
  JOB_STAGE_DESC	VARCHAR(250),
  ACTIVE          	BOOLEAN,
  DATE_CRT	      	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      	VARCHAR(20),
  DATE_MOD			TIMESTAMP,
  USER_MOD			VARCHAR(20)
);

ALTER TABLE JOB_STAGE ADD
  CONSTRAINT JOB_STAGE_PK
  PRIMARY KEY (JOB_STAGE);
  
  
CREATE TABLE TIMESHEET_CODE(
  TIMESHEET_CODE        VARCHAR(20),
  TIMESHEET_CODE_DESC	VARCHAR(250),
  ACTIVE          		BOOLEAN,
  DATE_CRT				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      		VARCHAR(20),
  DATE_MOD				TIMESTAMP,
  USER_MOD				VARCHAR(20)
);

ALTER TABLE TIMESHEET_CODE ADD
  CONSTRAINT TIMESHEET_CODE_PK
  PRIMARY KEY (TIMESHEET_CODE);
  

CREATE TABLE USERS(
  USER_ID         	VARCHAR(20),
  FIRST_NAME		VARCHAR(50),
  LAST_NAME       	VARCHAR(50),
  ACTIVE          	BOOLEAN,
  DATE_CRT	      	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      	VARCHAR(20),
  DATE_MOD			TIMESTAMP,
  USER_MOD			VARCHAR(20)
);

ALTER TABLE USERS ADD
  CONSTRAINT USERS_PK
  PRIMARY KEY (USER_ID);

ALTER TABLE USERS
ADD COLUMN PWORD VARCHAR(60);

CREATE TABLE JOBS(
  JOB_NO          		INT,
  JOB_NAME		  		VARCHAR(100),
  JOB_DESC		  		VARCHAR(4000),
  JOB_TYPE        		VARCHAR(20),
  JOB_PRIORITY        	VARCHAR(20),
  JOB_STATUS        	VARCHAR(20),
  JOB_RESOLUTION        VARCHAR(20),
  JOB_STAGE        		VARCHAR(20),
  JOB_REF 				VARCHAR(100),
  JOB_ORDER				INT,
  ASSIGNED_TO      		VARCHAR(20),
  TIMESHEET_CODE  		VARCHAR(20),
  ESTIMATED_HRS   		REAL,
  COMPLETED_HRS 		REAL,
  ESTIMATED_START_DATE 	TIMESTAMP,
  ACTUAL_START_DATE 	TIMESTAMP,
  ESTIMATED_END_DATE 	TIMESTAMP,
  ACTUAL_END_DATE 		TIMESTAMP,
  PARENT_JOB_NO 		INT,
  ACTIVE          		BOOLEAN,
  DATE_CRT	      		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      		VARCHAR(20),
  DATE_MOD				TIMESTAMP,
  USER_MOD				VARCHAR(20)
);

ALTER TABLE JOBS ADD
  CONSTRAINT JOBS_PK
  PRIMARY KEY (JOB_NO);
  
ALTER TABLE JOBS ADD
	CONSTRAINT JOBS_UC 
	UNIQUE (JOB_NAME);
  
CREATE SEQUENCE JOB_NO_SEQ START WITH 1;


CREATE TABLE TIMESHEET(
  TIMESHEET_ID		VARCHAR(100),
  USER_ID          	VARCHAR(20),
  JOB_NO          	INT,
  WORKED_DATE		TIMESTAMP,
  WORKED_HRS     	REAL,
  TIMESHEET_CODE	VARCHAR(250),
  ACTIVE          	BOOLEAN,
  DATE_CRT	      	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_CRT	      	VARCHAR(20),
  DATE_MOD			TIMESTAMP,
  USER_MOD			VARCHAR(20)
);

ALTER TABLE TIMESHEET ADD
  CONSTRAINT TIMESHEET_PK
  PRIMARY KEY (TIMESHEET_ID);
  
ALTER TABLE TIMESHEET ADD
  CONSTRAINT TIMESHEET_USER_ID_FK
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
  
ALTER TABLE TIMESHEET ADD
  CONSTRAINT TIMESHEET_JOB_NO_FK
  FOREIGN KEY (JOB_NO) REFERENCES JOBS (JOB_NO);
 
ALTER TABLE TIMESHEET ADD
	CONSTRAINT TIMESHEET_UC 
	UNIQUE (USER_ID, JOB_NO, WORKED_DATE);
	
CREATE TABLE LOGIN_HIST(
  HIST_ID           VARCHAR(100),
  USER_ID          	VARCHAR(20),
  IP_ADDR	        VARCHAR(20),
  DATE_CRT	      	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE LOGIN_HIST ADD
  CONSTRAINT LOGIN_HIST_PK
  PRIMARY KEY (HIST_ID);

ALTER TABLE LOGIN_HIST ADD
  CONSTRAINT LOGIN_HIST_USER_ID_FK
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
	
-- DATA -----------------------------------------------------------------------------

INSERT INTO USERS(USER_ID, FIRST_NAME, LAST_NAME, ACTIVE, DATE_CRT, PWORD)
VALUES('ADMIN', 'Admin', NULL, TRUE, CURRENT_TIMESTAMP, 'admin');


INSERT INTO JOB_PRIORITY(JOB_PRIORITY, JOB_PRIORITY_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('High', 'High Priority', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_PRIORITY(JOB_PRIORITY, JOB_PRIORITY_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Medium', 'Medium Priority', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_PRIORITY(JOB_PRIORITY, JOB_PRIORITY_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Low', 'Low Priority', TRUE, CURRENT_TIMESTAMP, 'ADMIN');


INSERT INTO JOB_RESOLUTION(JOB_RESOLUTION, JOB_RESOLUTION_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Done', 'Completed or fixed', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_RESOLUTION(JOB_RESOLUTION, JOB_RESOLUTION_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Duplicate', 'Same as another job', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_RESOLUTION(JOB_RESOLUTION, JOB_RESOLUTION_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Not Clear', 'Description is not clear', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_RESOLUTION(JOB_RESOLUTION, JOB_RESOLUTION_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Not Replicated', 'Issue cannot be replicated', TRUE, CURRENT_TIMESTAMP, 'ADMIN');


INSERT INTO JOB_STAGE(JOB_STAGE, JOB_STAGE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Design', 'Requirements gathering and high level design', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STAGE(JOB_STAGE, JOB_STAGE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Development', 'Detailed level design, coding and unit testing', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STAGE(JOB_STAGE, JOB_STAGE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Testing', 'Integrated testing', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STAGE(JOB_STAGE, JOB_STAGE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Deployment', 'Deploy to other environments (Test, Prod)', TRUE, CURRENT_TIMESTAMP, 'ADMIN');


INSERT INTO JOB_STATUS(JOB_STATUS, JOB_STATUS_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Scheduled', 'Scheduled to be commenced', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STATUS(JOB_STATUS, JOB_STATUS_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('In Progress', 'Work in progress', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STATUS(JOB_STATUS, JOB_STATUS_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('On Hold', 'On hold for some reason', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STATUS(JOB_STATUS, JOB_STATUS_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Completed', 'Completed with some resolution', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STATUS(JOB_STATUS, JOB_STATUS_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Pending', 'Pending for someone or something', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_STATUS(JOB_STATUS, JOB_STATUS_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Cancelled', 'Cancelled, not required any more', TRUE, CURRENT_TIMESTAMP, 'ADMIN');


INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Project', 'Job to group some tasks as a Project', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Task', 'Task is part of a project', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Bug', 'Standalone bug or issue, not part of a project', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Enhancement', 'Standalone enhancement, not part of a project', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Support', 'Investigating and issue or assisting someone, not part of a project', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Meeting', 'Meeting, not part of any job', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Leave', 'Annaul, Sick leaves', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO JOB_TYPE(JOB_TYPE, JOB_TYPE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('Adhoc', 'Ad hoc job', TRUE, CURRENT_TIMESTAMP, 'ADMIN');


INSERT INTO TIMESHEET_CODE(TIMESHEET_CODE, TIMESHEET_CODE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('ZZ01', 'Reviews/Meetings', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO TIMESHEET_CODE(TIMESHEET_CODE, TIMESHEET_CODE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('ZZ02', 'Sick Leave', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO TIMESHEET_CODE(TIMESHEET_CODE, TIMESHEET_CODE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('ZZ03', 'Annual Leve', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO TIMESHEET_CODE(TIMESHEET_CODE, TIMESHEET_CODE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('ZZ04', 'Public Holiday', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO TIMESHEET_CODE(TIMESHEET_CODE, TIMESHEET_CODE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('ZZ05', 'Staff Training', TRUE, CURRENT_TIMESTAMP, 'ADMIN');

INSERT INTO TIMESHEET_CODE(TIMESHEET_CODE, TIMESHEET_CODE_DESC, ACTIVE, DATE_CRT, USER_CRT)
VALUES('ZZ11', 'Sales Support', TRUE, CURRENT_TIMESTAMP, 'ADMIN');
